config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
    }
  get "home", to: 'articles#index', as: "user_root"
  resources :users, :only => [:index, :show]
  devise_scope :user do
    root :to => "devise/registrations#new"
  end
  resources :blogs

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :blog
  paginates_per 10
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :articles
  has_many :blog_tag_relations
  has_many :tags, through: :blog_tag_relations
end

app/models/blog_tag_relation.rb
class BlogTagRelation < ActiveRecord::Base
  belongs_to :blog
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :blog_tag_relations
  has_many :blogs, through: :blog_tag_relations
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
          uid:      auth.uid,
          provider: auth.provider,
          email:    User.dummy_email(auth),
          password: Devise.friendly_token[0, 20],
          image: auth.info.image,
          name: auth.info.name
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.includes(:blog).order("published DESC").page(params[:page])
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @articles = Article.order("published DESC")
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    # respond_to do |format|
      if @article.save
        rendar json: { status: 'success'}
        # format.html { redirect_to @article, notice: 'Article was successfully created.' }
        # format.json { render :show, status: :created, location: @article }
      else
        rendar json: { status: 'error'}
        # format.html { render :new }
        # format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    # end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :url, :blog_id)
    end

    def authenticate_user!
      session[:user_return_to] = env['PATH_INFO']
      redirect_to user_omniauth_authorize_path(:twitter) unless user_signed_in?
    end
end

app/controllers/blogs_controller.rb
# require "feedbag"
require "feedjira"
before_action :authenticate_user!

class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @articles = @blog.articles.order("published DESC")
    @tags = @blog.tags
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.create(blog_params)
    Feedjira::Feed.add_common_feed_element 'image'
    feed = Feedjira::Feed.fetch_and_parse(@blog.feed)
    @blog.last_modified = feed.last_modified
    @blog.blog_description = feed.description
    feed.entries.each do |entry|
      @blog.articles.create(name: entry.title, url: entry.url, article_description: entry.summary, published: entry.published, updated: entry.updated)
    end

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:name, :url, :feed)
    end

    def authenticate_user!
      session[:user_return_to] = env['PATH_INFO']
      redirect_to user_omniauth_authorize_path(:twitter) unless user_signed_in?
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # , :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  # def set_article
  #   @article = User.find(params[:id])
  # end

  # Never trust parameters from the scary internet, only allow the white list through.
  # def article_params
  #   params.require(:user).permit(:name, :url, :blog_id)
  # end

  def authenticate_user!
    session[:user_return_to] = env['PATH_INFO']
    redirect_to user_omniauth_authorize_path(:twitter) unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def link_to_next_page(scope, name, options = {}, &block)
    param_name = options.delete(:param_name) || Kaminari.config.param_name
    link_to_unless scope.last_page?, name, {param_name => (scope.current_page + 1)}, options.merge(:rel => 'next') do
      block.call if block
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/articles/_articles.html.erb
<% @articles.each do |article| %>
    <div class="media">
        <span class="media-left">
                      <!--<img src="http://lorempixel.com/40/40/people/1/">-->
                    </span>

        <div class="media-body">
            <p>
                <small><%= article.published.strftime("%Y/%m/%d") %></small>
                        <span class="pull-right like-button">
                          <button type="button" class="btn btn-link">
                              <i class="glyphicon glyphicon-folder-open"></i>
                          </button>
                        </span>
            </p>
            <p class="media-heading article-name">
                <a href="<%= article.url %>" target="_blank"><%= article.name %></p></a>
            <p class="pull-right">
                <small>Posted by</small>
                <span><a href="blogs/<%= article.blog_id %>"><%= article.blog.name %></a></span>
            </p>
        </div>
    </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :blog_id %><br>
    <%= f.number_field :blog_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container article-container">
  <div class="row">
      <div class="tab-pane active" id="feeds">
      <div class="col-sm-9">
        <ul class="nav nav-tabs top-tabs">
          <li class="active"><a href="#newarraival" data-toggle="tab">新着</a></li>
          <li><a href="#myfeed" data-toggle="tab">マイフィード</a></li>
        </ul>
        <div class="tab-content">
          <!--新着-->
          <div class="tab-pane active" id="newarraival">
            <div class="comments-list" id="articles-list">
                <%= render :partial => "articles" %>
            </div>
            <div class="btn-more text-center">
              <%= link_to_next_page @articles, 'もっと見る', :remote => true, :class => 'btn btn-default btn-block', :id => 'view_more' %>
            </div>
          </div>
          <!--マイフィード-->
          <!--<div class="tab-pane" id="myfeed">-->
            <!--<div class="comments-list">-->
              <!--<% @articles.each do |article| %>-->
                  <!--<div class="media">-->
                    <!--<span class="media-left">-->
                      <!--&lt;!&ndash;<img src="http://lorempixel.com/40/40/people/1/">&ndash;&gt;-->
                    <!--</span>-->

                    <!--<div class="media-body">-->
                      <!--<p>-->
                        <!--<small><%= article.published.strftime("%Y/%m/%d") %></small>-->
                        <!--<small class="pull-right">-->
                          <!--<button type="button" class="btn btn-link like-button">-->
                            <!--<i class="glyphicon glyphicon-heart-empty"></i></button>-->
                        <!--</small>-->
                      <!--</p>-->
                      <!--<p class="media-heading article-name">-->
                        <!--<a href="<%= article.url %>" target="_blank"><%= article.name %></p></a>-->
                      <!--<p>-->
                        <!--<small>Posted by</small>-->
                        <!--<span><a href="blogs/<%= article.blog_id %>"><%= article.blog.name %></a></span>-->
                      <!--</p>-->
                    <!--</div>-->
                  <!--</div>-->
              <!--<% end %>-->
            <!--</div>-->
          <!--</div>-->
        </div>
      </div>
      </div>
      <!--サイドバー-->
      <div class="col-sm-3">
        <div class="list-group">
          <%= link_to "フィード", root_path, class: 'list-group-item'%>
          <%= link_to "イベント", root_path, class: 'list-group-item' %>
          <%= link_to "ブログ登録", new_blog_path, class: 'list-group-item' %>
        </div>
      </div>
    </div>
  </div>

app/views/articles/index.js.erb
$("#articles-list").append("<%= j(render :partial => 'articles') %>");

$("#view_more").replaceWith("<%= escape_javascript(
    link_to_next_page(@articles, 'もっと見る', :remote => true, :class => 'btn btn-default btn-block', :id => 'view_more')
) %>");

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @article.url %>
</p>

<p>
  <strong>Blog:</strong>
  <%= @article.blog_id %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_area :url %>
  </div>
  <div class="field">
    <%= f.label :feed %><br>
    <%= f.text_area :feed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Feed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.name %></td>
        <td><%= blog.url %></td>
        <td><%= blog.feed %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">ブログ登録</h3>
    </div>
    <div class="panel-body">


      <%= form_for(@blog) do |f| %>
          <div class="form-group">
            <div class="row">
              <div class="col-md-6">
                <!--<%= text_field_tag :name, '', class: 'form-control', placeholder: 'ブログ名' %>-->
                <%= f.text_field :name, class: 'form-control', placeholder: 'ブログ名' %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-md-6">
                <!--<%= text_field_tag 'url', '', class: 'form-control', placeholder: 'URL' %>-->
                <%= f.text_field :url, class: 'form-control', placeholder: 'URL' %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-md-6">
                <!--<%= text_field_tag 'feed', '', class: 'form-control', placeholder: 'RSS' %>-->
                <%= f.text_field :feed, class: 'form-control', placeholder: 'RSS' %>
              </div>
            </div>
          </div>
          <!--<div class="form-group">-->
          <!--<div class="row">-->
          <!--<div class="col-md-6">-->
          <!--<input type="email" class="form-control" placeholder="メールアドレス">-->
          <!--</div>-->
          <!--</div>-->
          <!--</div>-->
          <!--<div class="form-group">-->
            <!--<div class="row">-->
              <!--<div class="col-md-4">-->
                <!--<select class="select-tags" multiple="multiple">-->
                  <!--<option value="AL">PHP</option>-->
                  <!--<option value="WY">Ruby</option>-->
                  <!--<option value="PL">Play framework2</option>-->
                  <!--<option value="SC">Scala</option>-->
                  <!--<option value="JA">Java</option>-->
                  <!--<option value="HD">Hadoop</option>-->
                  <!--<option value="SP">Spark</option>-->
                <!--</select>-->
              <!--</div>-->
            <!--</div>-->
          <!--</div>-->
          <div class="col-md-2">
            <!--<button type="submit" class="btn btn-success">登録する</button>-->
            <%= f.submit '登録する', class: 'btn btn-success' %>
          </div>
      <% end %>
      <!--</form>-->
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="container">
  <div class="page-header text-center">
    <h1 class="blogtitle" id="timeline"><a href="<%= @blog.url %>" target="_blank"><%= @blog.name %></a></h1>
    <p><%= @blog.blog_description %></p>
    <% @tags.each do |tag| %>
        <li>
          <a href="#" class="btn btn-default btn-xs"><%= tag.name %></a>
        </li>
    <% end %>
    <p class="feedbutton text-right">
      <a href="#" class="btn btn-success" id="like-feed-blog" role="button"><i class="glyphicon glyphicon-plus">このブログをフィード</i></a></p>
  </div>
  <ul class="timeline">
    <% @articles.each do |article| %>
    <li class="<%= cycle('', 'timeline-inverted') %>">
      <div class="timeline-badge primary"><a><i class="glyphicon glyphicon-adjust" rel="tooltip" title="<%= article.published.strftime("%Y/%m/%d") %>" id=""></i></a></div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <!--<img class="img-responsive" src="http://lorempixel.com/1600/500/sports/2" />-->
        </div>
        <div class="timeline-body">
          <p><b><a href="<%= article.url %>" target="_blank"><%= truncate(article.name, length: 200) %></a></b></p>
          <p><%= truncate(article.article_description, length: 150) %></p>
        </div>

        <div class="timeline-footer">
          <a><i class="glyphicon glyphicon-heart-empty"></i></a>
          <span class="pull-right"><%= article.published.strftime("%Y/%m/%d") %></span>
        </div>
      </div>
    </li>

    <!--<li  class="timeline-inverted">-->
      <!--<div class="timeline-badge primary"><a><i class="glyphicon glyphicon-record invert" rel="tooltip" title="11 hours ago via Twitter" id=""></i></a></div>-->
      <!--<div class="timeline-panel">-->
        <!--<div class="timeline-heading">-->
          <!--&lt;!&ndash;<img class="img-responsive" src="http://lorempixel.com/1600/500/sports/2" />&ndash;&gt;-->
        <!--</div>-->
        <!--<div class="timeline-body">-->
          <!--<p>Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis.</p>-->

        <!--</div>-->

        <!--<div class="timeline-footer">-->
          <!--<a><i class="glyphicon glyphicon-thumbs-up"></i></a>-->
          <!--<a><i class="glyphicon glyphicon-share"></i></a>-->
          <!--<a class="pull-right">Continuar Lendo</a>-->
        <!--</div>-->
      <!--</div>-->
    <!--</li>-->
    <% end %>
    <li class="clearfix" style="float: none;"></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>hackness</title>
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css' %>
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag 'http://yui.yahooapis.com/3.17.2/build/cssreset/cssreset-min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
    <%= javascript_include_tag 'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js' %>
    <%= javascript_include_tag 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js' %>
    <%= analytics_init if Rails.env.production? %>

    <%= csrf_meta_tags %>

    <!-- Bootstrap -->
    <!--<link href="css/bootstrap.css" rel="stylesheet">-->
    <!--<link href="css/typeaheadjs.css" rel="stylesheet">-->
    <!--&lt;!&ndash; カスタマイズ用CSS &ndash;&gt;-->
    <!--<link rel="stylesheet" media="screen" href="css/bootstrap-custom.css">-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
<body>
<div class="wrap">
<%= render 'shared/header' %>
<%= yield %>
<%= render 'shared/footer' %>
</div>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
<script src="js/typeahead.js"></script>
<script src="js/jquery.glanceyear.min.js"></script>
<script>
    $(".select-tags").select2();

    var massive = [
        {date: '2014-8-3', value:'1'},
        {date: '2014-8-4', value:'2'},
        {date: '2014-9-3', value:'3'},
        {date: '2014-10-14', value:'2'},
        {date: '2014-10-13', value:'8'},
        {date: '2014-7-3', value:'1'},
        {date: '2014-7-4', value:'2'},
        {date: '2014-7-7', value:'3'},
        {date: '2014-7-14', value:'2'},
        {date: '2014-6-3', value:'1'},
        {date: '2014-6-4', value:'2'},
        {date: '2014-6-5', value:'3'},
        {date: '2014-6-14', value:'2'}
    ];
    $('div#js-glanceyear').glanceyear(massive,
            {
                eventClick: function(e) { $('#debug').html('Date: '+ e.date + ', Count: ' + e.count); },
                months: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
                weeks: ['M','T','W','T','F','S', 'S'],
                showToday: false,
                today: new Date()
            });

</script>
</body>
</html>

app/views/shared/_footer.erb
<div class="footer">
    <div class="container">
        <p class="text-center">
            <a href="/">© <%= Time.now.year %> Hackness</a>
        </p>
    </div>
</div>

app/views/shared/_header.erb
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">
              Hackness
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <% if user_signed_in? %>
              <li><%= link_to "ブログ登録", new_blog_path %></li>
              <% end %>
              <li>
                <form class="navbar-form navbar-left" action="/api/search" role="search" method="get">
                  <div class="form-group">
                    <input type="search" class="form-control" autocomplete="off" placeholder="Search on Hackness">
                  </div>
                </form>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <img class="img-rounded img-profile-icon" src=<%= current_user.image %>>
                            <span><%= current_user.name %></span>
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><%= link_to "マイページ", current_user %></li>
                            <li><%= link_to "スニペットを投稿", '#' %></li>
                            <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
                            <li class="divider"></li>
                            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                        </ul>
                    </li>
                <% else %>
                    <li>
                      <%= link_to "ログイン", new_user_session_path %>
                    </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/users/index.html.erb
<% @users.each do |user| %>
<p><%= user.id %></p>
<p><%= user.name %></p>
<p><%= user.email %></p>
<% end %>